name: registore
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  audioplayers: ^6.5.0
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.2
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1
  intl: ^0.20.2
  mobile_scanner: ^7.0.1
  path: ^1.9.1
  provider: ^6.1.5+1
  reactive_forms: ^18.1.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  uuid: ^4.5.1
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/success.mp3
    - assets/sounds/error.mp3
    - assets/sounds/checkout.mp3
    - assets/sounds/decrement.mp3
